version: 2
updates:
# https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/terraform/examples/complete"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/src"
    schedule:
      interval: "monthly"